title: Hackathon 2019
meta_author: <CANAL TECH/>
gh_repo: "https://github.com/canalplus/hackathon2019"


# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FFF #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 3bc1c2 #2c3e50
  secondary-dark: 111 #233140 #233140
  tertiary: 174C4C #00EFEF

# Footer settings
footer:
  copyright: Dr. Henry Jekyll
  location: Location
  social: Around the Web
  credits: Credits

camp:
  date: 7-8 Novembre 2019
  key-words: LEAD THE CHANGE
  apply-form: https://forms.office.com

# Social Sharing
twitter:
  username : CanalTechTeam
dailymotion:
  username: plusdedev
medium:
  username : canal-tech
github:
  username: canalplus